### PR TITLE
License and documentation

### PR DESCRIPTION
**Pull request by AnujSaha0111**
Added LICENSE and documentation

### CODE REVIEW

**Comment by AnujSaha0111** [comment]
Was it merged? or any correction required?

**Comment by sk66641** [comment]
@AnujSaha0111 
Please see [Guidelines](https://github.com/sk66641/AquaGuardians?tab=readme-ov-file#getting-started) once

**Comment by AnujSaha0111** [comment]
is it any assign issue?

**Comment by sk66641** [comment]
@AnujSaha0111 
yes, we are advised to create a pr only if it's assigned

**Pull request closed without merging**
